version: "3.7"

services:
  db:
    image: postgres:12
    restart: unless-stopped
    environment:
      POSTGRES_DB: chronicles
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
