version: "3.7"

services:
  db:
    image: postgres:12
    restart: unless-stopped
    volumes:
      - pg_data:/var/lib/postgresql/data/pg_data
      - backup:/backup
    environment:
      POSTGRES_DB: chronicles
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
  app:
    image: bneibaruch/chronicles:latest
    restart: unless-stopped
    networks:
      - backend
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      DB_URL: postgres://${DB_USER}:${DB_PASSWORD}@db/mdb?sslmode=disable
      GIN_SERVER_MODE: production
    logging:
      options:
        max-size: '12m'
        max-file: '5'
        driver: json-file
    command: [ "/wait-for", "db:5432", "--", "./chronicles", "server" ]


networks:
  backend:

volumes:
  pg_data:
  backup:
